
version: '3.8'
services:
  backend:
    container_name: backend
    build: ../backend
    command: uvicorn app:app --host 0.0.0.0 --port 8000
    volumes:
      - ../backend:/app
    environment:
      - DATABASE_URL=sqlite:///app.db
    ports:
      - "8000:8000"
    networks:
      - webnet
  frontend:
    build: ../frontend
    command: npm run preview
    volumes:
      - ../frontend:/app
    ports:
      - "5173:5173"
    networks:
      - webnet
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - frontend
    networks:
      - webnet
  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot:/etc/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 6h & wait $${!}; certbot renew; done;'"
    depends_on:
      - nginx
    networks:
      - webnet
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: passionforchrist
      POSTGRES_USER: pfcuser
      POSTGRES_PASSWORD: changeme
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - webnet
volumes:
  db_data:
networks:
  webnet:
